/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Data.GUI;

import static Data.GUI.MainPage.Ruler;
import static Data.GUI.MainPage.allPeople;
import Data.PersonalData;
import static java.lang.Integer.parseInt;
import java.util.List;


/**
 *
 * @author ehear
 */
public class NewUser extends javax.swing.JFrame {

    /**
     * Creates new form NewUser
     */
    public NewUser() {
        initComponents();
        successButton.setVisible(false);
        errorButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnHomeButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        idNumberInput = new javax.swing.JTextField();
        firstNameInput = new javax.swing.JTextField();
        middleNameInput = new javax.swing.JTextField();
        lastNameInput = new javax.swing.JTextField();
        addressInput = new javax.swing.JTextField();
        cityInput = new javax.swing.JTextField();
        stateInput = new javax.swing.JTextField();
        zipcodeInput = new javax.swing.JTextField();
        phoneInput = new javax.swing.JTextField();
        cellInput = new javax.swing.JTextField();
        userNameInput = new javax.swing.JTextField();
        userPasswordInput = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        successButton = new javax.swing.JLabel();
        errorButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        returnHomeButton.setText("Return Home");
        returnHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnHomeButtonActionPerformed(evt);
            }
        });

        finishButton.setText("Finish");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Number");

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("First Name");

        jLabel3.setText("Middle Name");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Last Name");

        jLabel5.setText("Address");

        jLabel6.setText("City");

        jLabel7.setText("State");

        jLabel8.setText("Zip Code");

        jLabel9.setText("Phone #");

        jLabel10.setText("Cell Phone");

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("User Name");

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Password");

        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("Red text boxes required");

        successButton.setForeground(new java.awt.Color(0, 153, 0));
        successButton.setText("Success!");

        errorButton.setForeground(new java.awt.Color(255, 0, 0));
        errorButton.setText("Please fill out required fields");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(middleNameInput)
                            .addComponent(lastNameInput)
                            .addComponent(idNumberInput, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addressInput)
                            .addComponent(cityInput)
                            .addComponent(stateInput)
                            .addComponent(zipcodeInput)
                            .addComponent(phoneInput))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(userPasswordInput, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                            .addComponent(userNameInput)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cellInput, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(successButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(errorButton)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(returnHomeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10)
                    .addComponent(idNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11)
                    .addComponent(firstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12)
                    .addComponent(middleNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(lastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addressInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(stateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(zipcodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(phoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(successButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finishButton)
                    .addComponent(returnHomeButton))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnHomeButtonActionPerformed
        // TODO add your handling code here:
        MainPage mainPage = new MainPage();
        mainPage.setVisible(true);
        dispose();
    }//GEN-LAST:event_returnHomeButtonActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        // TODO add your handling code here:
        if(firstNameInput.getText().isEmpty() || lastNameInput.getText().isEmpty() || userNameInput.getText().isEmpty() || userPasswordInput.getText().isEmpty()){
            idNumberInput.setText("");
            firstNameInput.setText("");
            middleNameInput.setText("");
            lastNameInput.setText("");
            addressInput.setText("");
            cityInput.setText("");
            stateInput.setText("");
            zipcodeInput.setText("");
            phoneInput.setText("");
            cellInput.setText("");
            userNameInput.setText("");
            userPasswordInput.setText("");
            errorButton.setVisible(true);

        }
        else {
            if(!idNumberInput.getText().isEmpty())
                newUser.setId(parseInt(idNumberInput.getText()));
            if(!firstNameInput.getText().isEmpty())
                newUser.setFirstName(firstNameInput.getText());
            if(!middleNameInput.getText().isEmpty())
                newUser.setMiddleName(middleNameInput.getText());
            if(!lastNameInput.getText().isEmpty())
                newUser.setLastName(lastNameInput.getText());
            if(!addressInput.getText().isEmpty())
                newUser.setAddress(addressInput.getText());
            if(!cityInput.getText().isEmpty())
                newUser.setCity(cityInput.getText());
            if(!stateInput.getText().isEmpty())
                newUser.setState(stateInput.getText());
            if(!zipcodeInput.getText().isEmpty())
                newUser.setZipcode(parseInt(zipcodeInput.getText()));
            if(!phoneInput.getText().isEmpty())
                newUser.setPhoneNumber(parseInt(phoneInput.getText()));
            if(!cellInput.getText().isEmpty())
                newUser.setCellPhoneNumber(parseInt(cellInput.getText()));
            if(!userNameInput.getText().isEmpty())
                newUser.setUserName(userNameInput.getText());
            if(!userPasswordInput.getText().isEmpty())
                newUser.setUserPassword(userPasswordInput.getText());
            
            successButton.setVisible(true);
            errorButton.setVisible(false);
            
            idNumberInput.setText("");
            firstNameInput.setText("");
            middleNameInput.setText("");
            lastNameInput.setText("");
            addressInput.setText("");
            cityInput.setText("");
            stateInput.setText("");
            zipcodeInput.setText("");
            phoneInput.setText("");
            cellInput.setText("");
            userNameInput.setText("");
            userPasswordInput.setText("");
            
            allPeople2.add(newUser);
            
            for(int i = 0; i < allPeople.size(); i++)
            {
                Ruler.printPeople(allPeople.get(i));
            }
        }
         
    }//GEN-LAST:event_finishButtonActionPerformed

    public List<PersonalData> updateList(){
        return allPeople2;
    }
    
    
   
    
    MainPage temp = new MainPage();
    List<PersonalData> allPeople2 = temp.returnAllUsers();
    PersonalData newUser = new PersonalData(null,null,-1,null,null);
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressInput;
    private javax.swing.JTextField cellInput;
    private javax.swing.JTextField cityInput;
    private javax.swing.JLabel errorButton;
    private javax.swing.JButton finishButton;
    private javax.swing.JTextField firstNameInput;
    private javax.swing.JTextField idNumberInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameInput;
    private javax.swing.JTextField middleNameInput;
    private javax.swing.JTextField phoneInput;
    private javax.swing.JButton returnHomeButton;
    private javax.swing.JTextField stateInput;
    private javax.swing.JLabel successButton;
    private javax.swing.JTextField userNameInput;
    private javax.swing.JTextField userPasswordInput;
    private javax.swing.JTextField zipcodeInput;
    // End of variables declaration//GEN-END:variables
}
